site_name: Pictify
site_url: https://docs.pictify.io
site_description: Pictify is a simple and easy-to-use html to image and Gif API.
theme:
  name: material
  palette:
    primary: black
  logo: assets/logo.png
  favicon: assets/icon.png
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Example Code: example-code.md
  - FAQ: faq.md
extra_css:
  - stylesheets/extra-styles.css
extra:
  generator: false